repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'npx eslint --fix "$@"' --
        language: system
        types: [file]
        files: \.(js|jsx)$

      - id: prettier
        name: prettier
        entry: bash -c 'npx prettier --write "$@"' --
        language: system
        types: [file]
        files: \.(js|jsx|json|css|md)$
